development:
  adapter: postgresql
  database: autocadhelp
  username: adelaida
  password: Jgus83igy
  encoding: utf8
  reconnect: true

test:
  adapter: postgresql
  database: autocadhelptest
  username: adelaida
  password: Jgus83igy
  encoding: utf8
  reconnect: true

production:
  adapter: postgresql
  database: autocadhelp
  username: adelaida
  password: Jgus83igy
  encoding: utf8
  reconnect: true
