development:
  adapter: mysql2
  host: 127.0.0.1
  database: autocadhelp
  username: autocadhelp
  password: Gnash67perl
  encoding: utf8
  reconnect: true

test:
  adapter: mysql2
  host: 127.0.0.1
  database: autocadhelptest
  username: autocadhelp
  password: Gnash67perl
  encoding: utf8
  reconnect: true

production:
  adapter: mysql2
  host: 127.0.0.1
  database: autocadhelp
  username: autocadhelp
  password: Gnash67perl
  encoding: utf8
  reconnect: true
